---

- name: timezone
  hosts: all
  gather_facts: False
  become: true
  vars:
    hostname: "siduser106-wrkstn"
    tz: "Asia/Tokyo"
  tasks:
    - name: Set timezone
      timezone:
        name: "{{ tz }}"
    - name: Display timezone
      shell date +%Z
    - name: Set hostname
      hostname:
        name: "{{ hostname }}"
